"""create tables

Revision ID: f141af4e78c5
Revises: 
Create Date: 2025-10-15 14:54:29.484894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f141af4e78c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.Enum('free_individual', 'pro_individual', 'team', 'organization', 'enterprise', name='plantype'), nullable=False),
    sa.Column('price_monthly', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_submissions', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_forms', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('idx_plan_type', 'subscription_plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_config_updated', 'system_config', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'enumerator', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_token_name')
    )
    op.create_index('idx_token_active', 'api_tokens', ['is_active'], unique=False)
    op.create_index('idx_token_user', 'api_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('form_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('template_definition', sa.JSON(), nullable=False),
    sa.Column('preview_image', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_category', 'form_templates', ['category'], unique=False)
    op.create_index('idx_template_public', 'form_templates', ['is_public'], unique=False)
    op.create_index('idx_template_usage', 'form_templates', ['usage_count'], unique=False)
    op.create_index(op.f('ix_form_templates_id'), 'form_templates', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('submission', 'assignment', 'comment', 'system', 'webhook', 'report', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['type'], unique=False)
    op.create_index('idx_notification_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_organization_owner', 'organizations', ['owner_id'], unique=False)
    op.create_index('idx_organization_slug', 'organizations', ['slug'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('sync_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_submissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('synced', 'pending', 'error', name='syncstatusenum'), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'user_id', name='uq_device_user')
    )
    op.create_index('idx_sync_status', 'sync_status', ['status'], unique=False)
    op.create_index('idx_sync_user', 'sync_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_status_id'), 'sync_status', ['id'], unique=False)
    op.create_table('user_quotas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('max_submissions', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('max_forms', sa.Integer(), nullable=False),
    sa.Column('used_submissions', sa.Integer(), nullable=False),
    sa.Column('used_storage_mb', sa.Integer(), nullable=False),
    sa.Column('used_forms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_quota_user', 'user_quotas', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_quotas_id'), 'user_quotas', ['id'], unique=False)
    op.create_table('api_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_logs_created', 'api_logs', ['created_at'], unique=False)
    op.create_index('idx_api_logs_status', 'api_logs', ['status_code'], unique=False)
    op.create_index('idx_api_logs_token', 'api_logs', ['token_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_invitation_email', 'organization_invitations', ['email'], unique=False)
    op.create_index('idx_invitation_org', 'organization_invitations', ['organization_id'], unique=False)
    op.create_index('idx_invitation_status', 'organization_invitations', ['status'], unique=False)
    op.create_index('idx_invitation_token', 'organization_invitations', ['token'], unique=False)
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='organizationrole'), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user')
    )
    op.create_index('idx_member_org', 'organization_members', ['organization_id'], unique=False)
    op.create_index('idx_member_role', 'organization_members', ['role'], unique=False)
    op.create_index('idx_member_user', 'organization_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('personal', 'organization', name='projecttype'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='projectstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='projectvisibility'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_creator', 'projects', ['created_by'], unique=False)
    op.create_index('idx_project_org', 'projects', ['organization_id'], unique=False)
    op.create_index('idx_project_status', 'projects', ['status'], unique=False)
    op.create_index('idx_project_type_status', 'projects', ['project_type', 'status'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscription_org', 'subscriptions', ['organization_id'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_user', 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('analytics_dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dashboard_project', 'analytics_dashboards', ['project_id'], unique=False)
    op.create_index('idx_dashboard_public', 'analytics_dashboards', ['is_public'], unique=False)
    op.create_index(op.f('ix_analytics_dashboards_id'), 'analytics_dashboards', ['id'], unique=False)
    op.create_table('external_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_active', 'external_services', ['is_active'], unique=False)
    op.create_index('idx_service_project', 'external_services', ['project_id'], unique=False)
    op.create_index('idx_service_type', 'external_services', ['service_type'], unique=False)
    op.create_index(op.f('ix_external_services_id'), 'external_services', ['id'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('form_definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='formstatus'), nullable=False),
    sa.Column('allow_offline', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form_project_created', 'forms', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_form_project_status', 'forms', ['project_id', 'status'], unique=False)
    op.create_index('idx_form_status', 'forms', ['status'], unique=False)
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'excel', 'csv', 'word', 'json', name='reportformat'), nullable=False),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('include_media', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_template_active', 'report_templates', ['is_active'], unique=False)
    op.create_index('idx_report_template_project', 'report_templates', ['project_id'], unique=False)
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('user_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'collector', 'manager', name='projectrole'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project')
    )
    op.create_index(op.f('ix_user_assignments_id'), 'user_assignments', ['id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_active', 'webhooks', ['is_active', 'project_id'], unique=False)
    op.create_index('idx_webhook_project', 'webhooks', ['project_id'], unique=False)
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('data_config', sa.JSON(), nullable=False),
    sa.Column('display_config', sa.JSON(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['analytics_dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_widget_dashboard', 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_table('data_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'json', 'xml', 'kml', 'spss', name='exportformat'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='exportstatus'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_export_created', 'data_exports', ['created_at'], unique=False)
    op.create_index('idx_export_form', 'data_exports', ['form_id'], unique=False)
    op.create_index('idx_export_requester', 'data_exports', ['requested_by'], unique=False)
    op.create_index('idx_export_status', 'data_exports', ['status'], unique=False)
    op.create_index(op.f('ix_data_exports_id'), 'data_exports', ['id'], unique=False)
    op.create_table('data_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_expires', 'data_summaries', ['expires_at'], unique=False)
    op.create_index('idx_summary_form_field', 'data_summaries', ['form_id', 'field_name'], unique=False)
    op.create_index('idx_summary_type', 'data_summaries', ['summary_type'], unique=False)
    op.create_index(op.f('ix_data_summaries_id'), 'data_summaries', ['id'], unique=False)
    op.create_table('form_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permissions', sa.Enum('view', 'collect', 'manage', name='formpermission'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'form_id', name='uq_user_form')
    )
    op.create_index(op.f('ix_form_assignments_id'), 'form_assignments', ['id'], unique=False)
    op.create_table('form_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('require_authentication', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_url')
    )
    op.create_index('idx_deployment_active', 'form_deployments', ['is_active'], unique=False)
    op.create_index('idx_deployment_form', 'form_deployments', ['form_id'], unique=False)
    op.create_index('idx_deployment_url', 'form_deployments', ['deployment_url'], unique=False)
    op.create_index(op.f('ix_form_deployments_id'), 'form_deployments', ['id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_label', sa.String(length=500), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'date', 'select_one', 'select_multiple', 'photo', 'audio', 'video', 'gps', name='fieldtype'), nullable=False),
    sa.Column('field_options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('validation_rules', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'field_name', name='uq_form_field')
    )
    op.create_index('idx_form_field_form', 'form_fields', ['form_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_form_fields_id'), 'form_fields', ['id'], unique=False)
    op.create_table('form_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('form_definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'version_number', name='uq_form_version')
    )
    op.create_index('idx_form_version_form', 'form_versions', ['form_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_form_versions_id'), 'form_versions', ['id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='reportstatus'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_job_requester', 'report_jobs', ['requested_by'], unique=False)
    op.create_index('idx_report_job_status', 'report_jobs', ['status'], unique=False)
    op.create_index('idx_report_job_template', 'report_jobs', ['template_id'], unique=False)
    op.create_index(op.f('ix_report_jobs_id'), 'report_jobs', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('submission_data', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'validated', 'rejected', name='submissionstatus'), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_date', 'submissions', ['submitted_at'], unique=False)
    op.create_index('idx_submission_device', 'submissions', ['device_id'], unique=False)
    op.create_index('idx_submission_form_status', 'submissions', ['form_id', 'status'], unique=False)
    op.create_index('idx_submission_location', 'submissions', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_submission_submitter', 'submissions', ['submitted_by'], unique=False)
    op.create_index('idx_submission_synced', 'submissions', ['synced_at'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_logs_attempted', 'webhook_logs', ['attempted_at'], unique=False)
    op.create_index('idx_webhook_logs_event', 'webhook_logs', ['event'], unique=False)
    op.create_index('idx_webhook_logs_retry', 'webhook_logs', ['next_retry_at'], unique=False)
    op.create_index('idx_webhook_logs_webhook', 'webhook_logs', ['webhook_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_table('calculated_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id')
    )
    op.create_index('idx_calculated_field', 'calculated_fields', ['field_id'], unique=False)
    op.create_index(op.f('ix_calculated_fields_id'), 'calculated_fields', ['id'], unique=False)
    op.create_table('encrypted_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=36), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index('idx_encrypted_key', 'encrypted_submissions', ['encryption_key_id'], unique=False)
    op.create_index('idx_encrypted_submission', 'encrypted_submissions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_encrypted_submissions_id'), 'encrypted_submissions', ['id'], unique=False)
    op.create_table('form_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_field_id', sa.String(length=36), nullable=False),
    sa.Column('child_field_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['child_field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_field_id', 'child_field_id', name='uq_parent_child_field')
    )
    op.create_index('idx_dependency_child', 'form_dependencies', ['child_field_id'], unique=False)
    op.create_index('idx_dependency_parent', 'form_dependencies', ['parent_field_id'], unique=False)
    op.create_index(op.f('ix_form_dependencies_id'), 'form_dependencies', ['id'], unique=False)
    op.create_table('form_logic',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('source_field_id', sa.String(length=36), nullable=False),
    sa.Column('logic_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logic_field', 'form_logic', ['source_field_id'], unique=False)
    op.create_index('idx_logic_form', 'form_logic', ['form_id'], unique=False)
    op.create_index('idx_logic_type', 'form_logic', ['logic_type'], unique=False)
    op.create_index(op.f('ix_form_logic_id'), 'form_logic', ['id'], unique=False)
    op.create_table('form_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('constraint_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'language', name='uq_field_language')
    )
    op.create_index('idx_translation_field', 'form_translations', ['field_id'], unique=False)
    op.create_index('idx_translation_form', 'form_translations', ['form_id', 'language'], unique=False)
    op.create_index(op.f('ix_form_translations_id'), 'form_translations', ['id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_field', 'media_files', ['field_name'], unique=False)
    op.create_index('idx_media_submission', 'media_files', ['submission_id'], unique=False)
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_table('validation_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_field', 'validation_rules', ['field_id'], unique=False)
    op.create_index('idx_validation_type', 'validation_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_index('idx_validation_type', table_name='validation_rules')
    op.drop_index('idx_validation_field', table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_index('idx_media_submission', table_name='media_files')
    op.drop_index('idx_media_field', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_form_translations_id'), table_name='form_translations')
    op.drop_index('idx_translation_form', table_name='form_translations')
    op.drop_index('idx_translation_field', table_name='form_translations')
    op.drop_table('form_translations')
    op.drop_index(op.f('ix_form_logic_id'), table_name='form_logic')
    op.drop_index('idx_logic_type', table_name='form_logic')
    op.drop_index('idx_logic_form', table_name='form_logic')
    op.drop_index('idx_logic_field', table_name='form_logic')
    op.drop_table('form_logic')
    op.drop_index(op.f('ix_form_dependencies_id'), table_name='form_dependencies')
    op.drop_index('idx_dependency_parent', table_name='form_dependencies')
    op.drop_index('idx_dependency_child', table_name='form_dependencies')
    op.drop_table('form_dependencies')
    op.drop_index(op.f('ix_encrypted_submissions_id'), table_name='encrypted_submissions')
    op.drop_index('idx_encrypted_submission', table_name='encrypted_submissions')
    op.drop_index('idx_encrypted_key', table_name='encrypted_submissions')
    op.drop_table('encrypted_submissions')
    op.drop_index(op.f('ix_calculated_fields_id'), table_name='calculated_fields')
    op.drop_index('idx_calculated_field', table_name='calculated_fields')
    op.drop_table('calculated_fields')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_webhook', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_retry', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_event', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_attempted', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index('idx_submission_synced', table_name='submissions')
    op.drop_index('idx_submission_submitter', table_name='submissions')
    op.drop_index('idx_submission_location', table_name='submissions')
    op.drop_index('idx_submission_form_status', table_name='submissions')
    op.drop_index('idx_submission_device', table_name='submissions')
    op.drop_index('idx_submission_date', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_report_jobs_id'), table_name='report_jobs')
    op.drop_index('idx_report_job_template', table_name='report_jobs')
    op.drop_index('idx_report_job_status', table_name='report_jobs')
    op.drop_index('idx_report_job_requester', table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_form_versions_id'), table_name='form_versions')
    op.drop_index('idx_form_version_form', table_name='form_versions')
    op.drop_table('form_versions')
    op.drop_index(op.f('ix_form_fields_id'), table_name='form_fields')
    op.drop_index('idx_form_field_form', table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_form_deployments_id'), table_name='form_deployments')
    op.drop_index('idx_deployment_url', table_name='form_deployments')
    op.drop_index('idx_deployment_form', table_name='form_deployments')
    op.drop_index('idx_deployment_active', table_name='form_deployments')
    op.drop_table('form_deployments')
    op.drop_index(op.f('ix_form_assignments_id'), table_name='form_assignments')
    op.drop_table('form_assignments')
    op.drop_index(op.f('ix_data_summaries_id'), table_name='data_summaries')
    op.drop_index('idx_summary_type', table_name='data_summaries')
    op.drop_index('idx_summary_form_field', table_name='data_summaries')
    op.drop_index('idx_summary_expires', table_name='data_summaries')
    op.drop_table('data_summaries')
    op.drop_index(op.f('ix_data_exports_id'), table_name='data_exports')
    op.drop_index('idx_export_status', table_name='data_exports')
    op.drop_index('idx_export_requester', table_name='data_exports')
    op.drop_index('idx_export_form', table_name='data_exports')
    op.drop_index('idx_export_created', table_name='data_exports')
    op.drop_table('data_exports')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_index('idx_widget_dashboard', table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_index('idx_webhook_project', table_name='webhooks')
    op.drop_index('idx_webhook_active', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_user_assignments_id'), table_name='user_assignments')
    op.drop_table('user_assignments')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_index('idx_report_template_project', table_name='report_templates')
    op.drop_index('idx_report_template_active', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_index('idx_form_status', table_name='forms')
    op.drop_index('idx_form_project_status', table_name='forms')
    op.drop_index('idx_form_project_created', table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_external_services_id'), table_name='external_services')
    op.drop_index('idx_service_type', table_name='external_services')
    op.drop_index('idx_service_project', table_name='external_services')
    op.drop_index('idx_service_active', table_name='external_services')
    op.drop_table('external_services')
    op.drop_index(op.f('ix_analytics_dashboards_id'), table_name='analytics_dashboards')
    op.drop_index('idx_dashboard_public', table_name='analytics_dashboards')
    op.drop_index('idx_dashboard_project', table_name='analytics_dashboards')
    op.drop_table('analytics_dashboards')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index('idx_subscription_user', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_org', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('idx_project_type_status', table_name='projects')
    op.drop_index('idx_project_status', table_name='projects')
    op.drop_index('idx_project_org', table_name='projects')
    op.drop_index('idx_project_creator', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_index('idx_member_user', table_name='organization_members')
    op.drop_index('idx_member_role', table_name='organization_members')
    op.drop_index('idx_member_org', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_id'), table_name='organization_invitations')
    op.drop_index('idx_invitation_token', table_name='organization_invitations')
    op.drop_index('idx_invitation_status', table_name='organization_invitations')
    op.drop_index('idx_invitation_org', table_name='organization_invitations')
    op.drop_index('idx_invitation_email', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index('idx_api_logs_token', table_name='api_logs')
    op.drop_index('idx_api_logs_status', table_name='api_logs')
    op.drop_index('idx_api_logs_created', table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index(op.f('ix_user_quotas_id'), table_name='user_quotas')
    op.drop_index('idx_quota_user', table_name='user_quotas')
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_sync_status_id'), table_name='sync_status')
    op.drop_index('idx_sync_user', table_name='sync_status')
    op.drop_index('idx_sync_status', table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index('idx_organization_slug', table_name='organizations')
    op.drop_index('idx_organization_owner', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_form_templates_id'), table_name='form_templates')
    op.drop_index('idx_template_usage', table_name='form_templates')
    op.drop_index('idx_template_public', table_name='form_templates')
    op.drop_index('idx_template_category', table_name='form_templates')
    op.drop_table('form_templates')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_index('idx_token_user', table_name='api_tokens')
    op.drop_index('idx_token_active', table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_config_updated', table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index('idx_plan_type', table_name='subscription_plans')
    op.drop_index('idx_plan_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
